language: node_js # 언어는 node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
    - npm install
script:
  - npm build
after_success:
  - firebase deploy --token $firebase_token
