export const transactions : OfficetelTransaction[] = [
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "경희궁의 아침 2단지",
        "dong": " 내수동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 85,
        "day": 1,
        "area": 32.43,
        "zip_number": "71",
        "area_code": 11110,
        "floor": 16
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "용비어천가",
        "dong": " 내수동",
        "deposit": "21,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 3,
        "area": 33,
        "zip_number": "75",
        "area_code": 11110,
        "floor": 13
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "광화문시대",
        "dong": " 내수동",
        "deposit": "22,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 70,
        "day": 3,
        "area": 56.56,
        "zip_number": "74",
        "area_code": 11110,
        "floor": 13
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "경희궁의 아침 4단지",
        "dong": " 내수동",
        "deposit": "13,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 75,
        "day": 10,
        "area": 56.48,
        "zip_number": "73",
        "area_code": 11110,
        "floor": 16
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "광화문시대",
        "dong": " 내수동",
        "deposit": "25,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 60,
        "day": 10,
        "area": 56.56,
        "zip_number": "74",
        "area_code": 11110,
        "floor": 6
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "용비어천가",
        "dong": " 내수동",
        "deposit": "28,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 11,
        "area": 37.56,
        "zip_number": "75",
        "area_code": 11110,
        "floor": 18
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "광화문시대",
        "dong": " 내수동",
        "deposit": "2,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 85,
        "day": 11,
        "area": 34.9,
        "zip_number": "74",
        "area_code": 11110,
        "floor": 2
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "용비어천가",
        "dong": " 내수동",
        "deposit": "8,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 50,
        "day": 13,
        "area": 28.19,
        "zip_number": "75",
        "area_code": 11110,
        "floor": 5
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "경희궁의 아침 2단지",
        "dong": " 내수동",
        "deposit": "20,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 85,
        "day": 14,
        "area": 57.8,
        "zip_number": "71",
        "area_code": 11110,
        "floor": 14
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "경희궁의 아침 2단지",
        "dong": " 내수동",
        "deposit": "35,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 14,
        "area": 57.8,
        "zip_number": "71",
        "area_code": 11110,
        "floor": 12
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "광화문시대",
        "dong": " 내수동",
        "deposit": "5,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 65,
        "day": 14,
        "area": 32.01,
        "zip_number": "74",
        "area_code": 11110,
        "floor": 5
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "광화문시대",
        "dong": " 내수동",
        "deposit": "24,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 10,
        "day": 16,
        "area": 40.26,
        "zip_number": "74",
        "area_code": 11110,
        "floor": 14
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "용비어천가",
        "dong": " 내수동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 90,
        "day": 17,
        "area": 37.56,
        "zip_number": "75",
        "area_code": 11110,
        "floor": 6
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "광화문시대",
        "dong": " 내수동",
        "deposit": "25,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 20,
        "area": 40.26,
        "zip_number": "74",
        "area_code": 11110,
        "floor": 9
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "경희궁의 아침 3단지",
        "dong": " 내수동",
        "deposit": "3,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 75,
        "day": 20,
        "area": 37.5,
        "zip_number": "72",
        "area_code": 11110,
        "floor": 11
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "광화문시대",
        "dong": " 내수동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 80,
        "day": 28,
        "area": 31.75,
        "zip_number": "74",
        "area_code": 11110,
        "floor": 9
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "용비어천가",
        "dong": " 내수동",
        "deposit": "23,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 31,
        "area": 41.34,
        "zip_number": "75",
        "area_code": 11110,
        "floor": 11
    },
    {
        "building_year": 2004,
        "year": 2020,
        "housing_complex": "BIZ-WELL 종로 오피스텔",
        "dong": " 익선동",
        "deposit": "500",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 65,
        "day": 22,
        "area": 23.14,
        "zip_number": "34",
        "area_code": 11110,
        "floor": 10
    },
    {
        "building_year": 2019,
        "year": 2020,
        "housing_complex": "드래곤팰리스",
        "dong": " 돈의동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 80,
        "day": 9,
        "area": 23.38,
        "zip_number": "41-1",
        "area_code": 11110,
        "floor": 6
    },
    {
        "building_year": 2006,
        "year": 2020,
        "housing_complex": "효성주얼리시티",
        "dong": " 인의동",
        "deposit": "34,500",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 13,
        "day": 3,
        "area": 73.79,
        "zip_number": "48-2",
        "area_code": 11110,
        "floor": 4
    },
    {
        "building_year": 2019,
        "year": 2020,
        "housing_complex": "리베르떼_연지",
        "dong": " 연지동",
        "deposit": "16,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 8,
        "area": 19.93,
        "zip_number": "222",
        "area_code": 11110,
        "floor": 8
    },
    {
        "building_year": 2019,
        "year": 2020,
        "housing_complex": "로얄파크뷰",
        "dong": " 연지동",
        "deposit": "26,500",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 17,
        "area": 37.18,
        "zip_number": "238-5",
        "area_code": 11110,
        "floor": 4
    },
    {
        "building_year": 2003,
        "year": 2020,
        "housing_complex": "반도 보라 아이비 타워",
        "dong": " 효제동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 65,
        "day": 19,
        "area": 26.58,
        "zip_number": "45",
        "area_code": 11110,
        "floor": 6
    },
    {
        "building_year": 2013,
        "year": 2020,
        "housing_complex": "\t(1392)\t",
        "dong": " 숭인동",
        "deposit": "12,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 2,
        "area": 20.18,
        "zip_number": "1392",
        "area_code": 11110,
        "floor": 4
    },
    {
        "building_year": 2016,
        "year": 2020,
        "housing_complex": "아폴리움 오피스텔",
        "dong": " 숭인동",
        "deposit": "12,600",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 4,
        "area": 15.2,
        "zip_number": "201-7",
        "area_code": 11110,
        "floor": 3
    },
    {
        "building_year": 2005,
        "year": 2020,
        "housing_complex": "동양파라빌",
        "dong": " 숭인동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 55,
        "day": 6,
        "area": 24.93,
        "zip_number": "1388",
        "area_code": 11110,
        "floor": 12
    },
    {
        "building_year": 2016,
        "year": 2020,
        "housing_complex": "아이비씨 호텔 앤 오피스텔",
        "dong": " 숭인동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 60,
        "day": 6,
        "area": 21.36,
        "zip_number": "1396",
        "area_code": 11110,
        "floor": 9
    },
    {
        "building_year": 2016,
        "year": 2020,
        "housing_complex": "아이비씨 호텔 앤 오피스텔",
        "dong": " 숭인동",
        "deposit": "13,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 9,
        "area": 21.45,
        "zip_number": "1396",
        "area_code": 11110,
        "floor": 9
    },
    {
        "building_year": 2014,
        "year": 2020,
        "housing_complex": "삼전솔하임4차",
        "dong": " 숭인동",
        "deposit": "3,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 39,
        "day": 11,
        "area": 19.17,
        "zip_number": "318-2",
        "area_code": 11110,
        "floor": 6
    },
    {
        "building_year": 2013,
        "year": 2020,
        "housing_complex": "그레이스탑",
        "dong": " 숭인동",
        "deposit": "3,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 40,
        "day": 13,
        "area": 20.16,
        "zip_number": "178-94",
        "area_code": 11110,
        "floor": 4
    },
    {
        "building_year": 2005,
        "year": 2020,
        "housing_complex": "동양파라빌",
        "dong": " 숭인동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 55,
        "day": 14,
        "area": 24.93,
        "zip_number": "1388",
        "area_code": 11110,
        "floor": 13
    },
    {
        "building_year": 2012,
        "year": 2020,
        "housing_complex": "삼전솔하임2차",
        "dong": " 숭인동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 50,
        "day": 15,
        "area": 19.18,
        "zip_number": "296-19",
        "area_code": 11110,
        "floor": 2
    },
    {
        "building_year": 2016,
        "year": 2020,
        "housing_complex": "아이비씨 호텔 앤 오피스텔",
        "dong": " 숭인동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 60,
        "day": 17,
        "area": 21.62,
        "zip_number": "1396",
        "area_code": 11110,
        "floor": 18
    },
    {
        "building_year": 2005,
        "year": 2020,
        "housing_complex": "동양파라빌",
        "dong": " 숭인동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 90,
        "day": 20,
        "area": 40.5,
        "zip_number": "1388",
        "area_code": 11110,
        "floor": 14
    },
    {
        "building_year": 2014,
        "year": 2020,
        "housing_complex": "삼전솔하임4차",
        "dong": " 숭인동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 55,
        "day": 21,
        "area": 19.17,
        "zip_number": "318-2",
        "area_code": 11110,
        "floor": 7
    },
    {
        "building_year": 2016,
        "year": 2020,
        "housing_complex": "아이비씨 호텔 앤 오피스텔",
        "dong": " 숭인동",
        "deposit": "13,500",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 21,
        "area": 21.62,
        "zip_number": "1396",
        "area_code": 11110,
        "floor": 11
    },
    {
        "building_year": 2013,
        "year": 2020,
        "housing_complex": "버넷하임1",
        "dong": " 숭인동",
        "deposit": "13,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 22,
        "area": 24.77,
        "zip_number": "1421",
        "area_code": 11110,
        "floor": 10
    },
    {
        "building_year": 2005,
        "year": 2020,
        "housing_complex": "경일오피스텔",
        "dong": " 숭인동",
        "deposit": "2,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 41,
        "day": 22,
        "area": 20.14,
        "zip_number": "1367",
        "area_code": 11110,
        "floor": 6
    },
    {
        "building_year": 2005,
        "year": 2020,
        "housing_complex": "동양파라빌",
        "dong": " 숭인동",
        "deposit": "12,500",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 30,
        "area": 24.93,
        "zip_number": "1388",
        "area_code": 11110,
        "floor": 5
    },
    {
        "building_year": 2016,
        "year": 2020,
        "housing_complex": "아이비씨 호텔 앤 오피스텔",
        "dong": " 숭인동",
        "deposit": "1,200",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 105,
        "day": 30,
        "area": 43.29,
        "zip_number": "1396",
        "area_code": 11110,
        "floor": 16
    },
    {
        "building_year": 2020,
        "year": 2020,
        "housing_complex": "블루카운티 숭인Ⅰ",
        "dong": " 숭인동",
        "deposit": "25,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 0,
        "day": 31,
        "area": 26.63,
        "zip_number": "217-16",
        "area_code": 11110,
        "floor": 8
    },
    {
        "building_year": 2017,
        "year": 2020,
        "housing_complex": "경희궁자이",
        "dong": " 교북동",
        "deposit": "1,000",
        "gu": "종로구",
        "month": 1,
        "monthly_rent": 84,
        "day": 4,
        "area": 25.91,
        "zip_number": "126",
        "area_code": 11110,
        "floor": 5
    }
]